import type { NutrientMeta } from "@/types/nutrition";

export const NUTRIENT_METADATA: Record<number, NutrientMeta> = {
  208: { name: "Calories", unit: "kcal", category: "Macros", isGoal: true },
  203: { name: "Protein", unit: "g", category: "Macros", dvSource: "drv", dvKey: "protein" },
  204: { name: "Total Fat", unit: "g", category: "Macros", dvSource: "drv", dvKey: "fat" },
  205: {
    name: "Total Carbohydrate",
    unit: "g",
    category: "Macros",
    dvSource: "drv",
    dvKey: "total_carbohydrate",
  },
  291: {
    name: "Dietary Fiber",
    unit: "g",
    category: "Macros",
    dvSource: "drv",
    dvKey: "dietary_fiber",
  },
  320: {
    name: "Vitamin A (RAE)",
    unit: "mcg RAE",
    category: "Vitamins",
    dvSource: "rdi",
    dvKey: "vitamin_a",
  },
  401: { name: "Vitamin C", unit: "mg", category: "Vitamins", dvSource: "rdi", dvKey: "vitamin_c" },
  328: { name: "Vitamin D", unit: "mcg", category: "Vitamins", dvSource: "rdi", dvKey: "vitamin_d" },
  323: { name: "Vitamin E", unit: "mg", category: "Vitamins", dvSource: "rdi", dvKey: "vitamin_e" },
  430: { name: "Vitamin K", unit: "mcg", category: "Vitamins", dvSource: "rdi", dvKey: "vitamin_k" },
  404: { name: "Thiamin (B1)", unit: "mg", category: "Vitamins", dvSource: "rdi", dvKey: "thiamin_b1" },
  405: {
    name: "Riboflavin (B2)",
    unit: "mg",
    category: "Vitamins",
    dvSource: "rdi",
    dvKey: "riboflavin_b2",
  },
  406: {
    name: "Niacin (B3)",
    unit: "mg NE",
    category: "Vitamins",
    dvSource: "rdi",
    dvKey: "niacin_b3",
    fallback: 409,
  },
  415: { name: "Vitamin B6", unit: "mg", category: "Vitamins", dvSource: "rdi", dvKey: "vitamin_b6" },
  435: {
    name: "Folate (DFE)",
    unit: "mcg DFE",
    category: "Vitamins",
    dvSource: "rdi",
    dvKey: "folate_dfe",
    fallback: 417,
  },
  418: { name: "Vitamin B12", unit: "mcg", category: "Vitamins", dvSource: "rdi", dvKey: "vitamin_b12" },
  301: { name: "Calcium", unit: "mg", category: "Minerals", dvSource: "rdi", dvKey: "calcium" },
  303: { name: "Iron", unit: "mg", category: "Minerals", dvSource: "rdi", dvKey: "iron" },
  306: { name: "Potassium", unit: "mg", category: "Minerals", dvSource: "rdi", dvKey: "potassium" },
  304: { name: "Magnesium", unit: "mg", category: "Minerals", dvSource: "rdi", dvKey: "magnesium" },
  309: { name: "Zinc", unit: "mg", category: "Minerals", dvSource: "rdi", dvKey: "zinc" },
  307: { name: "Sodium", unit: "mg", category: "Minerals", dvSource: "drv", dvKey: "sodium" },
};

export const TRACKED_CODES = Object.keys(NUTRIENT_METADATA).map(Number);
